spring:
  application:
    name: Baiters Burger - Products API
  datasource:
    url: ${DATABASE_CONNECTION_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect: ${DATABASE_HIBERNATE_DIALECT}
server:
    port: 8080